### ISSUE TITLE
Error when build in react native 0.48.4

### ISSUE THREAD

**Issue by hagianga21** [innFactory/react-native-api-ai#15]
When I try to build your example in react native 0.48.4 there was an error : "cannot find symbol new RNApiAiPackage() and :app:compileDebugJavaWithJavac FAILED". Could you please help me to fix it ? Thank you

**Comment by spoeck** [comment]
Make sure that the linking was successful. 
In your Android app/build.gradle: 
```
dependencies {
    compile project(':react-native-api-ai')
 ...
}
```
and in your settings.gradle:
```
...
include ':react-native-api-ai'
project(':react-native-api-ai').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-api-ai/android')
...
```

**Comment by hagianga21** [comment]
Thank you, I fixed it, just add:    
dependencies {
    compile project(':react-native-api-ai')
 ...
}
